<Project>
  <PropertyGroup>
    <FoundationVersion>0.2.2</FoundationVersion>
    <Version>$(FoundationVersion)</Version>
    <PackageVersion>$(FoundationVersion)</PackageVersion>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <RepositoryUrl>https://github.com/orbyss-io/dotnet-foundation</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Authors>Orbyss</Authors>
    <Company>Orbyss</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' != 'Orbyss.Foundation.Analyzers'">
    <ProjectReference Include="$(MSBuildThisFileDirectory)src/Orbyss.Foundation.Analyzers/Orbyss.Foundation.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
