<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup><IsPackable>false</IsPackable></PropertyGroup>
<ItemGroup><PackageReference Include="CShells.AspNetCore" />
<ProjectReference Include="../../../src/Orbyss.Foundation.Web.HostedPages/Orbyss.Foundation.Web.HostedPages.csproj" />
</ItemGroup></Project>
