<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Optional default Problem Details exception and status handling for Orbyss Foundation CShells.</Description>
    <PackageId>Orbyss.Foundation.Web.ProblemDetails</PackageId>
    <PackageTags>orbyss-foundation;cshells;aspnetcore;problem-details</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="CShells.AspNetCore.Abstractions" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>
</Project>
